
CREATE TABLE IF NOT EXISTS diary (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    taskname TEXT NOT NULL,
    task TEXT NOT NULL DEFAULT '',
    deadline DATE NOT NULL DEFAULT None,
    status INTEGER NOT NULL DEFAULT 0 
)

